#!/usr/bin/env bash
# `cdk deploy --all` 직후 1회 실행. CFN describe-stacks로 App client id /
# Gateway URL을 뽑아 .mcp.json + .env.acharness를 생성한다.
#
# 사용:
#   ./scripts/bootstrap-env.sh                   # 기본 us-east-1
#   AWS_REGION=us-west-2 ./scripts/bootstrap-env.sh
#
# Idempotent. 스택이 아직 안 떠 있으면 명확하게 fail.
set -euo pipefail

REGION="${AWS_REGION:-us-east-1}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

q() {
  aws cloudformation describe-stacks \
    --region "$REGION" \
    --stack-name "$1" \
    --query "Stacks[0].Outputs[?OutputKey=='$2'].OutputValue | [0]" \
    --output text 2>/dev/null
}

CLIENT_ID="$(q AcharnessIdentityStack AppClientId)"
GATEWAY_URL="$(q AcharnessGatewayStack GatewayUrl)"

if [[ -z "$CLIENT_ID" || "$CLIENT_ID" == "None" ]]; then
  echo "AcharnessIdentityStack outputs not found in $REGION — run \`cdk deploy --all\` first" >&2
  exit 1
fi
if [[ -z "$GATEWAY_URL" || "$GATEWAY_URL" == "None" ]]; then
  echo "AcharnessGatewayStack outputs not found in $REGION — run \`cdk deploy --all\` first" >&2
  exit 1
fi

# 1. .env.acharness — get-mcp-token.sh가 source.
cat > "$ROOT/.env.acharness" <<EOF
# Auto-generated by scripts/bootstrap-env.sh. Do NOT commit.
ACHARNESS_CLIENT=$CLIENT_ID
ACHARNESS_REGION=$REGION
EOF
chmod 600 "$ROOT/.env.acharness" 2>/dev/null || true

# 2. .mcp.json — Claude Code가 읽는 MCP wiring.
cat > "$ROOT/.mcp.json" <<EOF
{
  "mcpServers": {
    "acharness-gateway": {
      "type": "http",
      "url": "$GATEWAY_URL",
      "headersHelper": "bash \${CLAUDE_PROJECT_DIR:-.}/scripts/get-mcp-token.sh"
    }
  }
}
EOF

echo "Wrote .env.acharness (CLIENT=$CLIENT_ID, REGION=$REGION)"
echo "Wrote .mcp.json   (URL=$GATEWAY_URL)"
echo ""
echo "Next:"
echo "  source scripts/switch-user.sh alice"
echo "  # then in Claude Code: /mcp -> acharness-gateway reconnect"
